services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: techchallenge-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - techchallenge-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: techchallenge-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - techchallenge-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: techchallenge-kafka-ui
    ports:
      - "3030:3030"
    restart: on-failure
    environment:
      - SERVER_PORT=3030
      - KAFKA_CLUSTERS_0_NAME=dev
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    networks:
      - techchallenge-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
    container_name: techchallenge-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - action.auto_create_index=false
      - ELASTICSEARCH_CLUSTER_NAME=techchallenge-elasticsearch-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - techchallenge-network
    restart: always

  redis:
    image: redis:latest
    container_name: techchallenge-redis
    ports:
      - "6379:6379"
    networks:
      - techchallenge-network
    restart: always

  app:
    build: .
    container_name: techchallenge-app
    depends_on:
      - kafka
      - elasticsearch
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_ELASTICSEARCH_URIS=elasticsearch:9200
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:29092
      - ELASTICSEARCH_INDEX_INITIALIZER_ENABLED=true
    networks:
      - techchallenge-network

networks:
  techchallenge-network:
    driver: bridge

volumes:
  techchallenge-data:
    driver: local
