app:
  swagger:
    server-url: http://localhost:8080
  cache:
    car-listings:
      ttl: 1m
  elasticsearch:
    index-initializer:
      enabled: ${ELASTICSEARCH_INDEX_INITIALIZER_ENABLED:true}
management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    elasticsearch:
      enabled: false
spring:
  elasticsearch:
    uris: localhost:9200
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: false
  cloud:
    config:
      enabled: false
    stream:
      bindings:
        carListings-in-0:
          destination: car_listings
          content-type: application/json
          group: tech_challenge_group
          consumer:
            max-attempts: 5
            back-off-initial-interval: 1000
            back-off-max-interval: 30000
            back-off-multiplier: 2.0
            retryable-exceptions:
              group.swissmarketplace.autoscout24.techchallenge.domain.model.exception.RetryableException: true
      kafka:
        binder:
          brokers:
            - localhost:9092
        bindings:
          carListings-in-0:
            consumer:
              autoCommitOnError: false
              enableDlq: true
              dlqName: car_listings_error
    function:
      definition: carListings
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
